# ===================================================================
# CONFIGURATION GENERALE DE L'APPLICATION
# ===================================================================
spring.application.name=colisender

# ===================================================================
# CONFIGURATION DE LA CONNEXION POSTGRESQL (Neon)
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-wandering-pine-as1zi7nu-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qM9YbiNVxc7k
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool (important pour Neon)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===================================================================
# EMAIL
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=miguelnzoukouo@gmail.com
spring.mail.password=nczh dgki asdp rktg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===================================================================
# JWT
# ===================================================================
jwt.secret=MaCleTresSecreteEtLongueDePlusDe32Caracteres!2026

# ===================================================================
# CAMPAY
# ===================================================================
campay.base-url=https://demo.campay.net/api
campay.app-username=JFdbS3MzoG_Hym3cZN65xKpjEJ3f
campay.app-password=ON44ChUc48ovI8Z6BGSQcjukN2Ep9Zf6N5XXDQOUnW5tZKSrDasKkzV8iS19A2uU7inAGcNKf8OY9YuuT9pgJg
campay.permanent-token=6ac01a347f4dfe2ddb4c4e2c9007a4c0063fd5d8

# ===================================================================
# FACE++
# ===================================================================
faceplusplus.api-key=Wqt70LFMOdoaTEonY8zybW65xKpjEJ3f
faceplusplus.api-secret=5brbkZm-18rB9tqbReIQ0s0tqzJGLkDZ
faceplusplus.seuil-confiance=70.0

# ===================================================================
# SERVEUR (Render injecte PORT automatiquement)
# ===================================================================
server.port=${PORT:8080}
server.address=0.0.0.0
